theme = TokyoNight
# alpha-blending= linear
background-opacity = 0.75

# term = xterm-256color
shell-integration-features = ssh-env,ssh-terminfo

font-family = "HackGen35 Console NF"
font-size = 14.0

keybind = ctrl+m=text:\x0D
keybind = ctrl+i=text:\x09
keybind = ctrl+[=text:\x1B
# keybind = ctrl+l=text:\x0C

mouse-shift-capture = true
